##
## Makefile for gnl in /home/jeremie/delivery/CPE/CPE_2016_getnextline/Test GNL
## 
## Made by jeremie bruhwiler
## Login   <jeremie@epitech.net>
## 
## Started on  Fri Jan 13 08:44:14 2017 jeremie bruhwiler
## Last update Sat Jan 14 21:50:56 2017 jeremie bruhwiler
##

SRC	=	my_putchar.c		\
		my_putstr.c		\
		../get_next_line.c	\
		test.c			\

OBJ	=	$(SRC:.c)

all:	$(OBJ)
	gcc $(SRC)

re:	all
